# Generated by Django 4.1.5 on 2023-01-23 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ToDoApp', '0002_alter_room_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user_room',
            field=models.ManyToManyField(default=False, related_name='user_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
