# Generated by Django 4.1.3 on 2022-11-20 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ToDoApp', '0003_alter_room_creator_id_alter_task_completed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nickname', models.CharField(max_length=30)),
                ('avatar', models.ImageField(default='media/default-avatar/avatar1.png', upload_to='media/avatars')),
                ('bio', models.TextField()),
            ],
        ),
    ]
