# Generated by Django 4.1.3 on 2022-11-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='media/default-avatar/avatar1.png', upload_to='media/avatars'),
        ),
    ]
